---
name: Build and Push docker image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest
    steps:

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: anewpoolio/cardano-submit-api

    - name: Loging to Docker hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker build
      uses: docker/build-push-action@v2
      with:
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
